### ISSUE TITLE
Suggestion: 3 suggestions about necrosis

### ISSUE THREAD

**Issue by reklaw9** [HaloSpaceStation/HaloSpaceStation13#2998] opened 2021-08-08 00:47 UTC
Suggestion: 1Make necrosis happen after 3 minutes of having severe organ damage and NOT getting treated

Suggestion 2:add a chemical which heals ALL organ damage extremely fast and heals necrosis but severely hinders the combat ability of the subject (for example, make it give severe amounts of pain as a side effect of make the subject go unscounscious until the chemical has done it's job)
 
Suggestion 3: simply remove necrosis

**Comment by Sgtwok** [comment] 2021-08-08 04:01
As much as I agree with you, this is unfortunately 100% intended.

**Comment by reklaw9** [comment] 2021-08-08 04:22
> As much as I agree with you, this is unfortunately 100% intended.

i know, this is a suggestion, not a bug report

**Comment by Sgtwok** [comment] 2021-08-08 07:47
Nor did I imply such.

This is still intended. You will not get them to budge.

**Comment by bloxgate** [comment] 2021-08-09 06:05
The current timer is two minutes. We can discuss changing it after the health tweaks to organs are put in, but I really don't think 1 extra minute will make a difference here. That said: Within those two minutes you can use peridaxon **surgically** to repair the organ. A single unit of peridaxon will instantly heal the organ if administered properly. You must do this manually - the autosurgeon is not capable of doing so.
![image](https://user-images.githubusercontent.com/2079324/128664423-21f07e31-ccdf-43e5-8f6b-51d58d94e0a9.png)

I have confirmed in code that this does restore dead organs to the alive status if the organ damage that caused the necrosis has been repaired prior to the administration of peridaxon and it is within the grace period:
https://github.com/HaloSpaceStation/HaloSpaceStation13/blob/alpha/code/modules/surgery/organs_internal.dm#L484
```dm
if(rejuvenate)
	affected.status &= ~ORGAN_DEAD
	affected.owner.update_body(1)
```

The tissue necrosis autoinjectors do **not** treat this condition: they treat organ damage before this point. I.e., they stop your organs from dying if you administer it **before** they reach the point of surgical intervention. You have to use surgery if a scanner says the organ is decaying.

We have discussed making some organs have more health, which is a separate issue, but I could give the heart or lungs 200 health just like brains and people would still complain about this so long as bad treatments/myths about how to deal with necrotic organs keep propagating. Here's how you should deal with this:
1. Administer the peridaxon autoinjectors and inaprovaline if it's available. This will help stop **other** organs from going necrotic and slow blood loss (if inaprovaline is given)
2. Check for a pulse. Administer tri-adrenaline, defib, or CPR is they don't have one.
3. Get the person to the hospital/infirmary, and check blood pressure. If blood pressure is below 75 over 51, start an IV instead of iron pills.
4. Surgically repair damage to organs using an advanced trauma kit
5. Surgically administer peridaxon to any necrotic organs - it'll tell you if they need further treatment or can't be revived at this point.
6. Replace any organ that couldn't be fixed by 5

I am quite confident that steps 3 - 6 can be done in under 2 minutes on a single person. The key here it to get the person to a place where surgery can be done within those two minutes.

**Comment by Aroliacue** [comment] 2023-01-24 13:41
Necrosis time has been increased. Can be closed

**Closed as completed** 2023-01-25 14:12 UTC
Labels: Suggestion, not a bug
