### ISSUE TITLE
Sewers sometimes loose air and pressure

### ISSUE THREAD

**Issue by PantasTheDank** [HaloSpaceStation/HaloSpaceStation13#1682] opened 2019-07-12 03:59 UTC
#### Description of issue

Sewers sometimes spawn with no air and pressure

#### Difference between expected and actual behavior

It should have air and pressure and no breachea

#### Steps to reproduce 

Its random

#### Length of time in which bug has been known to occur

N/A

#### Client version, Server revision & Game ID

N/A
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/HaloSpaceStation/HaloSpaceStation13/issues)

**Comment by caelaislinn** [comment] 2019-07-12 11:30
I put in a fix for this a week ago, and I double checked the fix. It's most likely related to the crystal caves but I can't reproduce anymore it in testing

**Closed as completed** 2019-10-24 15:55 UTC
Labels: bug, mapping
