### ISSUE TITLE
Kig'Yar (Possibly other Covvies) being infected by the Flood

### ISSUE THREAD

**Issue by ghost** [HaloSpaceStation/HaloSpaceStation13#640] opened 2018-06-04 09:20 UTC
#### Description of issue
When a Kig'Yar (Haven't seen with Unggoy or other covenant races, but I'd assume it's the same) is infected by the flood, a flood combat form is spawned (Has the human combat form sprite, but that's besides the point) but the Kig'Yar body remains

#### Difference between expected and actual behavior

The Kig'Yar body should be deleted/absorbed for use in the combat form instead of remaining.

#### Steps to reproduce 
-Infect a Kig'Yar (Possibly other covenant races as well)

#### Evidence
https://gyazo.com/438c28f36c4f77b07e214da7bb98fa6f
https://gyazo.com/1e320a0b73553dca88891d0c6c447d5b

**Comment by bloxgate** [comment] 2018-06-04 18:38
In lore grunts don't have sufficient biomass for combat forms and are converted into other forms, such as carriers, instead.

**Comment by X0-11** [comment] 2018-08-25 22:06
Looks like they can be infected but are better used as biomass.
http://halo.wikia.com/wiki/Flood_Combat_Form#Unggoy_and_Kig-Yar_Combat_Forms

**Comment by DexterDude** [comment] 2018-08-25 22:17
What Bloxgate said. Though they can be turned into flood forms but typically aren't as it's a waste of biomass, due to them being easily killed. Jackals are basically the same but moreso as they have extremly fragile bones.

**Comment by ghost** [comment] 2018-08-26 19:18
So make them be turned into carriers. The issue isn't that they ARE being infected and turned into combat forms, BUT the combat form is spawned, and they control it, but the original body isn't deleted, which I assume is a bug.

**Comment by X0-11** [comment] 2018-08-26 19:19
They turned into combat forms, I was merely providing something to support it. The issue is being looked at but I can't really see a reason why they wouldn't be deleted

**Comment by caelaislinn** [comment] 2018-11-25 02:25
I believe this was fixed in #870

**Closed as completed by caelaislinn** 2018-11-25 02:25 UTC
Labels: enhancement/QOL, Suggestion
