### ISSUE TITLE
Bayonets for the MA3 ( and other guns) 

### ISSUE THREAD

**Issue by Cynliax** [HaloSpaceStation/HaloSpaceStation13#1133] opened 2019-01-25 18:40 UTC
Self explanatory, bayonets that can be collapsible or affixed to the MA3 that if you're in close quarters, like a tile adjacent to an enemy, will do a stab equivalent to between knife-machete tier damage, could also work to damage doors.

**Comment by X0-11** [comment] 2019-01-28 09:58
Duplicate of #1063

**Closed as completed by X0-11** 2019-01-28 09:58 UTC
Labels: feature, Suggestion
