### ISSUE TITLE
Ship Crews of other vessels could not hear me from the Flagship despite being in visual range.

### ISSUE THREAD

**Issue by AttackHelicopter6784** [HaloSpaceStation/HaloSpaceStation13#2318] opened 2020-03-23 00:45 UTC
#### Description of issue
Other ships could not hear me issuing orders, despite being almost directly next to them via flagship. The issue resolved itself after ten minutes.

#### Difference between expected and actual behavior
Expected: Being able to communicate.
Actual: Not being able to communicate, and only be able to hear instead of also transmit. Others on the ship could hear me, but not other ships.

#### Steps to reproduce 
Unsure, it occurred without warning or reason.

#### Specific information for locating

Radios.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 01544599f363183a4bac962355e5a8d4f9287ff2 - alpha - 
Game ID: b6i-dDHY

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this

**Comment by caelaislinn** [comment] 2020-04-12 07:11
It looks like the first tcomms rewrite was reverted 6 days earlier, so it can't have been the cause of this. Has anyone seen it recur since?

**Comment by caelaislinn** [comment] 2020-06-05 03:05
Fixed with the tcomms rewrite

**Closed as completed by caelaislinn** 2020-06-05 03:05 UTC
Labels: bug
